library(rgdal)

Cities <- readOGR(dsn = "Deploy", layer = "Cities", GDAL1_integer64_policy = TRUE)
Filter_Coastal <- readOGR(dsn = "Deploy", layer = "Filter_Coastal", GDAL1_integer64_policy = TRUE)
Filter_Inland <- readOGR(dsn = "Deploy", layer = "Filter_Inland", GDAL1_integer64_policy = TRUE)
Filter_Rural <- readOGR(dsn = "Deploy", layer = "Filter_Rural", GDAL1_integer64_policy = TRUE)
Filter_Urban <- readOGR(dsn = "Deploy", layer = "Filter_Urban", GDAL1_integer64_policy = TRUE)
Filter_England <- readOGR(dsn = "Deploy", layer = "Filter_England", GDAL1_integer64_policy = TRUE)
Filter_Scotland <- readOGR(dsn = "Deploy", layer = "Filter_Scotland", GDAL1_integer64_policy = TRUE)
Filter_Wales <- readOGR(dsn = "Deploy", layer = "Filter_Wales", GDAL1_integer64_policy = TRUE)
RentDataPolygons <- readOGR(dsn = "Deploy", layer = "RentDataPolygons", GDAL1_integer64_policy = TRUE)
BRMA_BoundingTable <- read.csv(file ="Deploy/BRMA_BoundingTable.csv", header = TRUE, sep = ",")
RentDataTable <- read.csv(file ="Deploy/RentDataTable.csv", header = TRUE, sep = ",")
summaryTable <- read.csv(file ="Deploy/summaryTable.csv", header = TRUE, sep = ",")
